export type Project = {
  id: string;
  title: string;
  description: string;
  longDescription: string;
  images: string[];
  stack: string[];
  githubLink: string;
  liveLink?: string;
  features: string[];
  category?: "Personal" | "Client Work";
};

export const PROJECTS: Project[] = [
  {
    id: "baatchit",
    title: "Baatchit",
    description:
      "A production-ready real-time communication platform with custom-branded email verification and secure authentication.",
    longDescription:
      "Baatchit is a high-performance MERN stack application designed for seamless real-time interaction. It features a robust email verification system via Resend API, custom DNS configurations for high deliverability, and Socket.IO for sub-100ms message latency. The architecture includes secure JWT-based session management and a polished, responsive UI optimized for modern devices.",
    images: ["/baatchit2.webp", "/baatchit.webp"],
    stack: ["React", "MongoDB", "Socket.IO", "Node.js", "Express.js", "Resend", "JWT"],
    githubLink: "https://github.com/priyanshusc/Baatchit-App",
    liveLink: "https://baatchit.priyanshusc.tech/", // Added your new professional domain
    features: [
      "Real-time bidirectional messaging with Socket.IO",
      "Secure Email Verification system",
      "Production-grade DNS setup (SPF/DKIM) for high inbox deliverability",
      "Stateless authentication using JWT with secure password hashing via Bcrypt",
    ],
  },
  {
    id: "liveBite",
    title: "LiveBite",
    description:
      "A full-stack food court application for seamless ordering and real-time updates.",
    longDescription:
      "LiveBite is a comprehensive food ordering platform designed to streamline the dining experience. Built with MERN stack, it offers secure role-based access for students and administrators. Users can explore menus, manage their shopping carts, and track their orders with instant updates.",
    images: ["/livebite.webp", "/livebite2.webp"],
    stack: ["React", "Cloudinary", "JWT Auth", "Express.js", "Socket.IO", "Axios"],
    githubLink: "https://github.com/priyanshusc/livebite",
    features: [
      "Secure role-based authentication (User & Admin)",
      "Dynamic shopping cart and order management system",
      "Real-time order tracking and status updates via Socket.IO",
      "Seamless database integration with MongoDB and Cloudinary for media",
    ],
  },
  {
    id: "ai-skillpath",
    title: "AI SkillPath",
    description:
      "Personalized learning paths generated by AI based on user goals.",
    longDescription:
      "AI SkillPath leverages the power of generative AI to create customized roadmaps and learning paths for users looking to acquire new skills. By inputting your target skill and current level, the app curates a step-by-step curriculum.",
    images: ["/Skillpath.webp", "/Skillpath2.webp"],
    stack: ["React", "Django", "Gemini API"],
    githubLink: "https://github.com/priyanshusc/AI-SkillPath",
    features: [
      "AI-driven curriculum generation using Gemini API",
      "Structured learning roadmaps visualizing study paths",
      "Integration of Django REST Framework and React",
      "Secure user intent modeling",
    ],
  },
  {
    id: "mehfil",
    title: "Mehfil",
    description:
      "A full-stack music streaming platform with dual roles for listeners and artists.",
    longDescription:
      "Mehfil is a MERN stack music streaming platform with dual roles for listeners and artists. Artists upload tracks and album art via Cloudinary, while listeners like songs, follow artists, and build playlists — all with a persistent global audio player that never interrupts on navigation.",
    images: ["/mehfil.webp", "/mehfil2.webp"],
    stack: ["React", "Node.js", "Express.js", "MongoDB", "Cloudinary"],
    githubLink: "https://github.com/priyanshusc/Mehfil",
    // liveLink: "https://mehfil.vercel.app/",
    features: [
      "Dual-role system — Artists upload & manage music, Listeners discover & stream",
      "Persistent global audio player with uninterrupted playback across navigation",
      "Social features — Follow/unfollow artists, like/unlike songs, create playlists",
      "Cloudinary-powered media storage for audio tracks and album art uploads",
    ],
  },
  {
    id: "collabify",
    title: "Collabify",
    description:
      "A collaborative real-time tool with a shared workspace environment.",
    longDescription:
      "Collabify enables teams to work together in real-time. Integrating Y.js for CRDT-based operational transformations and Socket.IO for synchronization, the platform supports multiple users editing shared documents and boards without conflicts.",
    images: ["/Collabify2.webp", "/Collabify.webp"],
    stack: ["React", "Y.js", "Socket.IO", "Express.js", "Axios"],
    githubLink: "https://github.com/priyanshusc/Collabify",
    features: [
      "Conflict-free distributed collaboration via Y.js",
      "Real-time state synchronization with Socket.IO",
      "Extensible workspace for seamless team interactions",
      "Robust RESTful backend with Express.js",
    ],
  },
  {
    id: "leetquiz",
    title: "Leetquiz",
    description:
      "An AI-powered interviewer application for technical coding practice.",
    longDescription:
      "Leetquiz helps software engineers prepare for technical interviews. Powered by Mistral AI, it simulates real coding interviews by generating algorithm questions, evaluating answers, and providing constructive feedback like a real interviewer.",
    images: ["/Leetquiz.webp"],
    stack: ["React", "Tailwind CSS", "Mistral AI"],
    githubLink: "https://github.com/priyanshusc/Leetquiz-AI-Interviewer",
    features: [
      "AI evaluation of coding solutions",
      "Dynamic question generation based on difficulty",
      "Interactive coding environment simulation",
      "Sleek and accessible interface using Tailwind CSS",
    ],
  },
  {
    id: "netflix-clone",
    title: "Netflix Clone",
    description:
      "A feature-rich clone of Netflix with movie browsing and AI recommendations.",
    longDescription:
      "This Netflix Clone replicates the core user interface of the popular streaming platform. It integrates a TMDB API for real-time movie data and utilizes Firebase for secure user authentication. In addition, it features an AI-based search function that suggests movies.",
    images: ["/Netflix.webp"],
    stack: ["React", "Tailwind CSS", "Firebase", "Mistral AI"],
    githubLink: "https://github.com/priyanshusc/Netflix-Clone",
    features: [
      "TMDB API integration for a vast movie database",
      "Secure user authentication using Firebase",
      "AI-powered search mechanism",
      "Responsive layout mirroring the original Netflix UI",
    ],
  },
  // {
  //   id: "mindsphere",
  //   title: "MindSphere",
  //   description:
  //     "An interactive learning or mindfulness application using Flask and Gemini.",
  //   longDescription:
  //     "MindSphere is a unique web application blending psychological well-being or mind mapping with AI insights. Serving dynamic templates via Flask and stylizing them through Tailwind CSS, it offers users personalized interaction through the Gemini API.",
  //   images: ["/MindSphere.webp"],
  //   stack: ["Flask", "Tailwind CSS", "Gemini API", "Javascript"],
  //   githubLink: "https://github.com/priyanshusc/MindSphere",
  //   features: [
  //     "Python-powered backend with Flask",
  //     "Interactive data processing guided by Gemini API",
  //     "Lightweight Vanilla JavaScript for frontend logic",
  //     "Minimalistic styling with Tailwind CSS",
  //   ],
  // },
  // {
  //   id: "weather-app",
  //   title: "Weather App",
  //   description:
  //     "A lightweight application providing accurate, real-time weather forecasts.",
  //   longDescription:
  //     "A minimalist Weather Application offering instant weather updates around the globe. By fetching data from the OpenWeather API, it displays current temperatures, atmospheric conditions, and brief forecasts using a very clean aesthetic.",
  //   images: ["/Weather.webp"],
  //   stack: ["Javascript", "Tailwind CSS", "OpenWeather API"],
  //   githubLink: "https://github.com/priyanshusc/Weather-App",
  //   features: [
  //     "Real-time weather data retrieval via OpenWeather API",
  //     "Responsive design optimized for multiple devices",
  //     "Immediate search feedback via Vanilla Javascript",
  //     "Elegant styling elements via Tailwind CSS",
  //   ],
  // },
  {
    id: "chator-adda",
    title: "Chator Adda Cafe",
    description: "A responsive cafe website built for a local client to showcase menu and basic business information.",
    longDescription: "Chator Adda Cafe is a clean and modern frontend website developed for a local cafe client. The goal was to create a visually appealing and mobile-friendly site to display their menu, location, and contact details. The project focuses on UI/UX design, smooth animations, and responsiveness rather than complex backend functionality.",
    images: ["/ChatorAdda.webp", "/ChatorAdda2.webp"],
    stack: ["React", "Tailwind CSS", "Framer Motion"],
    githubLink: "https://github.com/priyanshusc/ChatorAdda-Cafe",
    liveLink: "https://chatoradda.vercel.app/",
    features: [
      "Fully responsive design for mobile, tablet, and desktop",
      "Clean and structured menu display",
      "Smooth animations using Framer Motion",
      "Simple and intuitive UI for better user experience",
    ],
    category: "Client Work",
  },
];

export type YoutubeVideo = {
  id: string;
  title: string;
  thumbnail: string;
  date: string;
  videoLink: string;
};

export const YOUTUBE_VIDEOS: YoutubeVideo[] = [
  {
    id: "yt-1",
    title: "Access Token vs Refresh Token",
    thumbnail: "/yt1.webp",
    date: "Jul 03, 2026",
    videoLink: "https://youtube.com/shorts/tmfWZ48BWgs?si=_Lj-5RlY3dW8cXXl",
  },
  {
    id: "yt-2",
    title: "New HTTP Method Query",
    thumbnail: "/yt2.webp",
    date: "Jul 05, 2026",
    videoLink: "https://youtube.com/shorts/b8p6-4e-4bs?si=1pZR2eY2yfSb_KSL",
  },
];